


tasks_A = {'MDTB09_Digit_Judgment', 'MDTB16_Finger_Sequence', 'MDTB15_Finger_Simple', 'MDTB02_Go', 'MDTB12_Happy_Faces', ...
    'MDTB13_Interval_Timing', 'MDTB08_Math', 'MDTB14_Motor_Imagery', 'MDTB01_No-Go', 'MDTB20_Object_2Back', 'MDTB10_Object_Viewing',...
    'MDTB07_Pleasant_Scenes', 'MDTB29_Rest', 'MDTB11_Sad_Faces', 'MDTB21_Spatial_Imagery', 'MDTB23_Stroop_Congruent', 'MDTB22_Stroop_Incongruent',...
    'MDTB03_Theory_Of_Mind', 'MDTB06_Unpleasant_Scenes', 'MDTB24_Verb_Generation', 'MDTB18_Verbal_2Back', 'MDTB04_Action_Observation',...
    'MDTB05_Video_Knots', 'MDTB26_Visual_Search_Small', 'MDTB28_Visual_Search_Large', 'MDTB27_Visual_Search_Medium', 'MDTB25_Word_Reading'};
tasks_B = {'MDTB38_Animated_Movie', ...
    'MDTB43_Biological_Motion',...
    'MDTB16_Finger_Sequence',...
    'MDTB15_Finger_Simple',...
    'MDTB39_Landscape_Movie',...
    'MDTB40_Mental_Rotation_Easy',...
    'MDTB42_Mental_Rotation_Hard',...
    'MDTB41_Mental_Rotation_Medium',...
    'MDTB37_Nature_Movie',...
    'MDTB20_Object_2Back',...
    'MDTB30_CPRO',...
    'MDTB31_Prediction',...
    'MDTB33_Prediction_Scrambled',...
    'MDTB32_Prediction_Violated',...
    'MDTB45_Response_Alternatives_Easy',...
    'MDTB47_Response_Alternatives_Hard',...
    'MDTB46_Response_Alternatives_Medium',...
    'MDTB29_Rest',...
    'MDTB44_Scrambled_Motion',...
    'MDTB21_Spatial_Imagery',...
    'MDTB34_Spatial_Map_Easy',...
    'MDTB36_Spatial_Map_Hard',...
    'MDTB35_Spatial_Map_Medium',...
    'MDTB03_Theory_Of_Mind',...
    'MDTB24_Verb_Generation',...
    'MDTB04_Action_Observation',...
    'MDTB05_Video_Knots',...
    'MDTB26_Visual_Search_Small',...
    'MDTB28_Visual_Search_Large',...
    'MDTB27_Visual_Search_Medium',...
    'MDTB25_Word_Reading'
    };


%% case 'DIR:create'
first_level_analysis('DIR:create')

%% case 'MULTICONDITION:create'

subjects = {'09'};

first_level_analysis('MULTICONDITION:create', subjects)

%% case 'ISOLATE:suit'

subjects = {'10', '12','14','15'};
runs = [1,2,3,4,5,6,7,8];
first_level_analysis('ISOLATE:suit', subjects)

% case 'NORMALISATION:suit'
first_level_analysis('NORMALISATION:suit', subjects)

% case 'SPM:split'
first_level_analysis('SPM:split', subjects, runs)

% case 'RESLICE:suit'
first_level_analysis('RESLICE:suit', subjects, runs)

%% case 'MODEL:specify'
subjects = {'18'};
runs = [1,2,3,4,5,6,7,8];
first_level_analysis('MODEL:specify', subjects,runs)

% case 'MODEL:estimate'

first_level_analysis('MODEL:estimate', subjects)


%% case 'CONTRAST:manager'

% here we define the contrasts we wants to see
% contrast = { {'name_contrast', [index_in_list_of_condition], {name_conditions}, [weight]} }
% note : there is to contrast (A and B) because there is two type of
%        session for this  particular experiment (King2019).
subjects = {'18'};

contrast_A = {{'IntervalTiming', [6,13], {'MDTB13_Interval_Timing','MDTB29_Rest' },[1,-1] },...
            {'IAPSemotion',[5,14,13],{'MDTB12_Happy_Faces', 'MDTB11_Sad_Faces','MDTB29_Rest' },[0.5,0.5,-1]}, ...
            {'IAPSaffective',[12,19,13], { 'MDTB06_Unpleasant_Scenes',  'MDTB07_Pleasant_Scenes','MDTB29_Rest' },[0.5,0.5,-1]}, ...
            {'GoNoGo',[4,9,13],{'MDTB01_No-Go', 'MDTB02_Go', 'MDTB29_Rest'},[0.5,0.5,-1]},...
            {'Rest',[13],{'MDTB29_Rest'},[1]}, ...
            {'MotorSequence',[2,3,13],{'MDTB16_Finger_Sequence', 'MDTB15_Finger_Simple','MDTB29_Rest'},[0.5,0.5,-1]},...         
            };
contrast_B = {
            {'Rest',[18],{'MDTB29_Rest'},[1]}, ...
            {'MotorSequence',[3,4,18],{'MDTB16_Finger_Sequence', 'MDTB15_Finger_Simple','MDTB29_Rest'},[0.5,0.5,-1]},... 
            {'RespAlt',[15,16,17,18],{'MDTB45_Response_Alternatives_Easy','MDTB28_Visual_Search_Large','MDTB27_Visual_Search_Medium','MDTB29_Rest'},[0.33,0.33,0.33,-1]}...
            };
        
        
        
contrast_task = {{'IntervalTiming', [6], {'MDTB13_Interval_Timing' },[1] },...
            {'MDTB12_Happy_Faces-vs-MDTB11_Sad_Faces',[5,14],{'MDTB12_Happy_Faces', 'MDTB11_Sad_Faces' },[1,-1]}, ...
            { 'MDTB06_Unpleasant_Scenes-vs-MDTB07_Pleasant_Scenes',[12,19], { 'MDTB06_Unpleasant_Scenes',  'MDTB07_Pleasant_Scenes'},[1,-1]}, ...
            {'MDTB01_No-Go-vs-MDTB02_Go',[4,9],{'MDTB01_No-Go', 'MDTB02_Go'},[1,-1]},...
            {'MDTB16_Finger_Sequence-vs-MDTB15_Finger_Simple',[2,3],{'MDTB16_Finger_Sequence', 'MDTB15_Finger_Simple'},[1,-1]},...         
            };
        
contrast_full = {{'IntervalTiming', [6,13], {'MDTB13_Interval_Timing','MDTB29_Rest' },[1,-1] },...
            {'IAPSemotion',[5,14,13],{'MDTB12_Happy_Faces', 'MDTB11_Sad_Faces','MDTB29_Rest' },[0.5,0.5,-1]}, ...
            {'IAPSaffective',[12,19,13], { 'MDTB06_Unpleasant_Scenes',  'MDTB07_Pleasant_Scenes','MDTB29_Rest' },[0.5,0.5,-1]}, ...
            {'GoNoGo',[4,9,13],{'MDTB01_No-Go', 'MDTB02_Go', 'MDTB29_Rest'},[0.5,0.5,-1]},...
            {'Rest',[13],{'MDTB29_Rest'},[1]}, ...
            {'MotorSequence',[2,3,13],{'MDTB16_Finger_Sequence', 'MDTB15_Finger_Simple','MDTB29_Rest'},[0.5,0.5,-1]},... 
            {'IntervalTiming', [6], {'MDTB13_Interval_Timing' },[1] },...
            {'MDTB12_Happy_Faces-vs-MDTB11_Sad_Faces',[5,14],{'MDTB12_Happy_Faces', 'MDTB11_Sad_Faces' },[1,-1]}, ...
            { 'MDTB06_Unpleasant_Scenes-vs-MDTB07_Pleasant_Scenes',[12,19], { 'MDTB06_Unpleasant_Scenes',  'MDTB07_Pleasant_Scenes'},[1,-1]}, ...
            {'MDTB01_No-Go-vs-MDTB02_Go',[4,9],{'MDTB01_No-Go', 'MDTB02_Go'},[1,-1]},...
            {'MDTB16_Finger_Sequence-vs-MDTB15_Finger_Simple',[2,3],{'MDTB16_Finger_Sequence', 'MDTB15_Finger_Simple'},[1,-1]}...
            };

% here we define the subjects and the contrasts.
contrasts = contrast_full;
first_level_analysis('CONTRAST:manager', subjects, contrasts )

%% case 'FLATMAP:save'

% here we save the contrast map spmT_XXX.nii in a flatmap of the
% cerebellum.

% here we define the subjects and the contrasts.
subjects = {'21'};
idx_contrast = [1,2,3,4,5,6,7,8,9,10,11];
contrasts = contrast_full;
display_ = false;

first_level_analysis('FLATMAP:save', subjects, idx_contrast, contrasts, display_)

%% case 'FLATMAP:display'

% here we define the subjects and the contrasts.

idx_contrast = [1,2,3,4,5,6,7,8,9,10,11];
contrasts = contrast_full;

subjects = {'21'};

% here we define the lut
MyMap = brewermap(126, 'RdBu');
myLut = flipud(MyMap);

first_level_analysis('FLATMAP:display', subjects, idx_contrast, contrasts, myLut)


